# Generated by Django 5.2.5 on 2025-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='shared_expenses', to='api.student'),
        ),
    ]
